variable "cluster_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "dns_prefix" {}
variable "aks_version" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "nodepool_name" {}
variable "admin_username" {}
variable "ssh_public_key" {}
variable "node_count" {}
variable "node_size" {}
variable "max_pods" {}
variable "osdisk_size" {}
variable "autoscaling_enabled" {}
variable "min_count" {}
variable "max_count" {}
variable "subnet_id" {}
