replicaCount: 1

image:
  repository: docker.registry/hello-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
